export const defaultCustomization: Types.Customization = {
  faceTecSessionTimerCustomization: {
    livenessCheckNoInteractionTimeout: 60,
    idScanNoInteractionTimeout: 120,
  },
  faceTecOCRConfirmationCustomization: {
    backgroundColors: ['#ffffff'],
    mainHeaderDividerLineColor: '#fd5a28',
    mainHeaderDividerLineWidth: -1,
    mainHeaderFont: null,
    mainHeaderTextColor: '#fd5a28',
    sectionHeaderFont: null,
    sectionHeaderTextColor: '#333333',
    fieldLabelFont: null,
    fieldLabelTextColor: '#333333',
    fieldValueFont: null,
    fieldValueTextColor: '#333333',
    inputFieldBackgroundColor: undefined,
    inputFieldFont: null,
    inputFieldTextColor: undefined,
    inputFieldBorderColor: '#333333',
    inputFieldBorderWidth: -1,
    inputFieldCornerRadius: -1,
    inputFieldPlaceholderFont: null,
    inputFieldPlaceholderTextColor: undefined,
    showInputFieldBottomBorderOnly: false,
    buttonFont: null,
    buttonTextNormalColor: undefined,
    buttonBackgroundNormalColor: '#fd5a28',
    buttonTextHighlightColor: undefined,
    buttonBackgroundHighlightColor: '#f07854',
    buttonTextDisabledColor: '#ffffff',
    buttonBackgroundDisabledColor: '#FAB2A5',
    buttonBorderColor: undefined,
    buttonBorderWidth: -1,
    buttonCornerRadius: 50,
  },

  faceTecIDScanCustomization: {
    showSelectionScreenBrandingImage: false,
    selectionScreenBrandingImage: undefined,
    showSelectionScreenDocumentImage: true,
    selectionScreenDocumentImage: undefined,
    captureScreenBackgroundColor: undefined,
    captureFrameStrokeColor: '#fd5a28',
    captureFrameStrokeWidth: -1,
    captureFrameCornerRadius: -1,
    activeTorchButtonImage: undefined,
    inactiveTorchButtonImage: undefined,
    selectionScreenBackgroundColors: undefined,
    selectionScreenForegroundColor: '#fd5a28',
    reviewScreenBackgroundColors: undefined,
    reviewScreenForegroundColor: undefined,
    reviewScreenTextBackgroundColor: '#fd5a28',
    reviewScreenTextBackgroundBorderColor: undefined,
    reviewScreenTextBackgroundBorderWidth: 0,
    reviewScreenTextBackgroundCornerRadius: -1,
    captureScreenForegroundColor: undefined,
    captureScreenTextBackgroundColor: '#fd5a28',
    captureScreenTextBackgroundBorderColor: undefined,
    captureScreenTextBackgroundBorderWidth: 0,
    captureScreenTextBackgroundCornerRadius: -1,
    captureScreenFocusMessageTextColor: '#333333',
    captureScreenFocusMessageFont: null,
    headerFont: null,
    subtextFont: null,
    buttonFont: null,
    buttonTextNormalColor: undefined,
    buttonBackgroundNormalColor: '#fd5a28',
    buttonTextHighlightColor: undefined,
    buttonBackgroundHighlightColor: '#f07854',
    buttonTextDisabledColor: '#ffffff',
    buttonBackgroundDisabledColor: '#FAB2A5',
    buttonBorderColor: undefined,
    buttonBorderWidth: -1,
    buttonCornerRadius: 40,

    customNFCStartingAnimation: 0,
    customNFCScanningAnimation: 0,
    customNFCCardStartingAnimation: 0,
    customNFCCardScanningAnimation: 0,
    customNFCSkipOrErrorAnimation: 0,
    customStaticNFCStartingAnimation: 0,
    customStaticNFCScanningAnimation: 0,
    customStaticNFCSkipOrErrorAnimation: 0,
  },

  faceTecOverlayCustomization: {
    backgroundColor: '#ffffff',
    brandingImage: undefined,
    showBrandingImage: false,
  },

  faceTecResultScreenCustomization: {
    animationRelativeScale: 1,
    foregroundColor: '#fd5a28',
    backgroundColors: ['#ffffff', '#ffffff'],
    activityIndicatorColor: '#fd5a28',
    customActivityIndicatorImage: undefined,
    customActivityIndicatorRotationInterval: 1000,
    customActivityIndicatorAnimation: 0,
    showUploadProgressBar: true,
    uploadProgressFillColor: '#fd5a28',
    uploadProgressTrackColor: '#00000033',
    resultAnimationBackgroundColor: '#fd5a28',
    resultAnimationForegroundColor: undefined,
    resultAnimationSuccessBackgroundImage: undefined,
    resultAnimationUnsuccessBackgroundImage: undefined,
    customResultAnimationSuccess: 0,
    customResultAnimationUnsuccess: 0,
    customStaticResultAnimationSuccess: 0,
    customStaticResultAnimationUnsuccess: 0,
    messageFont: null,
  },

  faceTecGuidanceCustomization: {
    backgroundColors: ['#ffffff', '#ffffff'],
    foregroundColor: '#ffffff',
    headerFont: null,
    subtextFont: null,
    readyScreenHeaderFont: null,
    readyScreenHeaderTextColor: undefined,
    readyScreenHeaderAttributedString: '',
    readyScreenSubtextFont: null,
    readyScreenSubtextTextColor: undefined,
    readyScreenSubtextAttributedString: '',
    retryScreenHeaderFont: null,
    retryScreenHeaderTextColor: undefined,
    retryScreenHeaderAttributedString: '',
    retryScreenSubtextFont: null,
    retryScreenSubtextTextColor: undefined,
    retryScreenSubtextAttributedString: '',
    buttonFont: null,
    buttonTextNormalColor: '#ffffff',
    buttonBackgroundNormalColor: '#fd5a28',
    buttonTextHighlightColor: undefined,
    buttonBackgroundHighlightColor: '#f07854',
    buttonTextDisabledColor: '#ffffff',
    buttonBackgroundDisabledColor: '#FAB2A5',
    buttonBorderColor: undefined,
    buttonBorderWidth: -1,
    buttonCornerRadius: -1,
    readyScreenOvalFillColor: '#00000000',
    readyScreenTextBackgroundColor: '#ffffff',
    readyScreenTextBackgroundCornerRadius: -1,
    retryScreenImageBorderColor: '#fd5a28',
    retryScreenImageBorderWidth: -1,
    retryScreenImageCornerRadius: -1,
    retryScreenOvalStrokeColor: undefined,
    retryScreenIdealImage: undefined,
    retryScreenSlideshowImages: undefined,
    retryScreenSlideshowInterval: 1500,
    enableRetryScreenSlideshowShuffle: true,
    cameraPermissionsScreenImage: undefined,
  },

  faceTecFrameCustomization: {
    borderWidth: undefined,
    cornerRadius: undefined,
    borderColor: '#ffffff',
    backgroundColor: '#ffffff',
    elevation: undefined,
  },

  faceTecFeedbackCustomization: {
    cornerRadius: 50,
    backgroundColors: ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
    textColor: '#000000',
    textFont: null,
    enablePulsatingText: true,
    elevation: 10,
  },

  faceTecOvalCustomization: {
    strokeWidth: 0,
    strokeColor: '#FFFFFFFF',
    progressStrokeWidth: 0,
    progressColor1: '#fd5a28',
    progressColor2: '#fd5a28',
    progressRadialOffset: 0,
  },

  faceTecCancelButtonCustomization: {
    location: 'topLeft',
    customImage: undefined,
  },

  faceTecExitAnimationStyle: {
    animation: 'circleFade',
  },
};
